inherit_from: .rubocop_todo.yml

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  SupportedStyles:
    - ruby19
    - hash_rockets

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/RegexpLiteral:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RescueModifier:
  Enabled: false
